In [1]:
def division_func(dividend, divisor):
    try:
        return (dividend/divisor)
    except ZeroDivisionError:
        print("Divisor should not be 0")
    
if __name__ == '__main__':
    a = (division_func(5, 0))
    if a is not None:
        print(a)

Divisor should not be 0


In [2]:
def sent_generator(subjects, verb, objects):
    sentence_list = [(sub + " " + ver + " " + obj + ".") for sub in subjects for ver in verb for obj in objects]
    return sentence_list

if __name__ == '__main__':
    subjects = input("Enter the subjects : ").split()
    verb = input("Enter the verb : ").split()
    objects = input("Enter the objects : ").split()
    sentence_list = sent_generator(subjects, verb, objects)
    for sent in sentence_list:
        print(sent)


Enter the subjects : Americans Indians
Enter the verb : play watch
Enter the objects : Cricket Basketball
Americans play Cricket.
Americans play Basketball.
Americans watch Cricket.
Americans watch Basketball.
Indians play Cricket.
Indians play Basketball.
Indians watch Cricket.
Indians watch Basketball.


In [3]:
import numpy as np
x = np.array([1, 2, 3, 5])
n = input("Enter the value of N : ")
N = int(n) if n is not "" else len(x) # When no value is provided it should create a square matrix of array size
# Method 1
print("Method 1: \n", np.column_stack([x**(N-1-i) for i in range(N)]))
print("*" * 60)
# Method 2
print("Method 2: \n", np.vander(x, N))

Enter the value of N : 3
Method 1: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
************************************************************
Method 2: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
